owner: integra-node # (Ejemplo: santiago-cardozo o el nombre de la organización)
repo: integranode-upptime # (Ejemplo: integranode-status)

# La configuración de la página web
user-agent: IntegraNode Uptime Monitor
status-website:
  cname: status.integranode.com # (Opcional: Si quieres usar un subdominio tuyo)
  name: IntegraNode Status
  introTitle: "**IntegraNode** Infrastructure Status"
  introMessage: Real-time uptime monitor and official status page for our industrial telemetry infrastructure.
  navbar:
    - title: Website
      href: https://app.integranode.com
    - title: GitHub
      href: https://github.com/santiago-integranode

sites:
  - name: App IntegraNode
    url: https://app.integranode.com
    expectedStatusCodes:
      - 200

  - name: Broker MQTT
    check: "tcp-ping"
    url: mqtt.integranode.com
    port: 8883

  # 3. Servicio UDP (Proxy Healthcheck) - PENDIENTE DE DESPLIEGUE EN PROD
  # - name: Telemetría (Servicio UDP)
  #   url: http://34.95.131.76:8080/healthz # Reemplazar con tu IP y puerto real
  #   expectedStatusCodes:
  #     - 200

  notifications:
    - type: google-chat
      endpoint: $GOOGLE_CHAT_WEBHOOK
